version: "3.8"

services:
  client:
    image: client-merntest
    build: ./client
    # stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - fullstackapp
    environment:
      - VITE_SERVER_URI={VITE_SERVER_URI}

    # env_file:
    #   - ./client/.env

  api-server:
    image: api-server-merntest
    build: ./server
    ports:
      - "3000:3000"
    networks:
      - fullstackapp
    depends_on:
      - db
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}

    # for testing out the prod on local machine
    # env_file:
    #   - ./server/.env

networks:
  fullstackapp:
    driver: bridge
